// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	config "github.com/shaharia-lab/agento/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// MockSettingsStore is an autogenerated mock type for the SettingsStore type
type MockSettingsStore struct {
	mock.Mock
}

type MockSettingsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettingsStore) EXPECT() *MockSettingsStore_Expecter {
	return &MockSettingsStore_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with no fields
func (_m *MockSettingsStore) Load() (config.UserSettings, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 config.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func() (config.UserSettings, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() config.UserSettings); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.UserSettings)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockSettingsStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockSettingsStore_Expecter) Load() *MockSettingsStore_Load_Call {
	return &MockSettingsStore_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockSettingsStore_Load_Call) Run(run func()) *MockSettingsStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSettingsStore_Load_Call) Return(_a0 config.UserSettings, _a1 error) *MockSettingsStore_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsStore_Load_Call) RunAndReturn(run func() (config.UserSettings, error)) *MockSettingsStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: settings
func (_m *MockSettingsStore) Save(settings config.UserSettings) error {
	ret := _m.Called(settings)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(config.UserSettings) error); ok {
		r0 = rf(settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettingsStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSettingsStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - settings config.UserSettings
func (_e *MockSettingsStore_Expecter) Save(settings interface{}) *MockSettingsStore_Save_Call {
	return &MockSettingsStore_Save_Call{Call: _e.mock.On("Save", settings)}
}

func (_c *MockSettingsStore_Save_Call) Run(run func(settings config.UserSettings)) *MockSettingsStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.UserSettings))
	})
	return _c
}

func (_c *MockSettingsStore_Save_Call) Return(_a0 error) *MockSettingsStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettingsStore_Save_Call) RunAndReturn(run func(config.UserSettings) error) *MockSettingsStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSettingsStore creates a new instance of MockSettingsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettingsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettingsStore {
	mock := &MockSettingsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
