with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
packages:
  github.com/shaharia-lab/agento/internal/storage:
    interfaces:
      AgentStore:
      ChatStore:
      IntegrationStore:
      TaskStore:
      TriggerStore:
  github.com/shaharia-lab/agento/internal/config:
    interfaces:
      SettingsStore:
  github.com/shaharia-lab/agento/internal/service:
    interfaces:
      AgentService:
      ChatService:
      IntegrationService:
      NotificationService:
      TaskService:
      TriggerService:
