// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	agent "github.com/shaharia-lab/agento/internal/agent"
	claude "github.com/shaharia-lab/claude-agent-sdk-go/claude"

	context "context"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/shaharia-lab/agento/internal/storage"
)

// MockChatService is an autogenerated mock type for the ChatService type
type MockChatService struct {
	mock.Mock
}

type MockChatService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatService) EXPECT() *MockChatService_Expecter {
	return &MockChatService_Expecter{mock: &_m.Mock}
}

// BeginMessage provides a mock function with given fields: ctx, sessionID, content, opts
func (_m *MockChatService) BeginMessage(ctx context.Context, sessionID string, content string, opts agent.RunOptions) (*claude.Session, *storage.ChatSession, error) {
	ret := _m.Called(ctx, sessionID, content, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginMessage")
	}

	var r0 *claude.Session
	var r1 *storage.ChatSession
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, agent.RunOptions) (*claude.Session, *storage.ChatSession, error)); ok {
		return rf(ctx, sessionID, content, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, agent.RunOptions) *claude.Session); ok {
		r0 = rf(ctx, sessionID, content, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*claude.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, agent.RunOptions) *storage.ChatSession); ok {
		r1 = rf(ctx, sessionID, content, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*storage.ChatSession)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, agent.RunOptions) error); ok {
		r2 = rf(ctx, sessionID, content, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockChatService_BeginMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginMessage'
type MockChatService_BeginMessage_Call struct {
	*mock.Call
}

// BeginMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - content string
//   - opts agent.RunOptions
func (_e *MockChatService_Expecter) BeginMessage(ctx interface{}, sessionID interface{}, content interface{}, opts interface{}) *MockChatService_BeginMessage_Call {
	return &MockChatService_BeginMessage_Call{Call: _e.mock.On("BeginMessage", ctx, sessionID, content, opts)}
}

func (_c *MockChatService_BeginMessage_Call) Run(run func(ctx context.Context, sessionID string, content string, opts agent.RunOptions)) *MockChatService_BeginMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(agent.RunOptions))
	})
	return _c
}

func (_c *MockChatService_BeginMessage_Call) Return(_a0 *claude.Session, _a1 *storage.ChatSession, _a2 error) *MockChatService_BeginMessage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockChatService_BeginMessage_Call) RunAndReturn(run func(context.Context, string, string, agent.RunOptions) (*claude.Session, *storage.ChatSession, error)) *MockChatService_BeginMessage_Call {
	_c.Call.Return(run)
	return _c
}

// BulkDeleteSessions provides a mock function with given fields: ctx, ids
func (_m *MockChatService) BulkDeleteSessions(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDeleteSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatService_BulkDeleteSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDeleteSessions'
type MockChatService_BulkDeleteSessions_Call struct {
	*mock.Call
}

// BulkDeleteSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockChatService_Expecter) BulkDeleteSessions(ctx interface{}, ids interface{}) *MockChatService_BulkDeleteSessions_Call {
	return &MockChatService_BulkDeleteSessions_Call{Call: _e.mock.On("BulkDeleteSessions", ctx, ids)}
}

func (_c *MockChatService_BulkDeleteSessions_Call) Run(run func(ctx context.Context, ids []string)) *MockChatService_BulkDeleteSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockChatService_BulkDeleteSessions_Call) Return(_a0 error) *MockChatService_BulkDeleteSessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatService_BulkDeleteSessions_Call) RunAndReturn(run func(context.Context, []string) error) *MockChatService_BulkDeleteSessions_Call {
	_c.Call.Return(run)
	return _c
}

// CommitMessage provides a mock function with given fields: ctx, session, assistantText, sdkSessionID, isFirstMessage, blocks, usage
func (_m *MockChatService) CommitMessage(ctx context.Context, session *storage.ChatSession, assistantText string, sdkSessionID string, isFirstMessage bool, blocks []storage.MessageBlock, usage agent.UsageStats) error {
	ret := _m.Called(ctx, session, assistantText, sdkSessionID, isFirstMessage, blocks, usage)

	if len(ret) == 0 {
		panic("no return value specified for CommitMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.ChatSession, string, string, bool, []storage.MessageBlock, agent.UsageStats) error); ok {
		r0 = rf(ctx, session, assistantText, sdkSessionID, isFirstMessage, blocks, usage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatService_CommitMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitMessage'
type MockChatService_CommitMessage_Call struct {
	*mock.Call
}

// CommitMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - session *storage.ChatSession
//   - assistantText string
//   - sdkSessionID string
//   - isFirstMessage bool
//   - blocks []storage.MessageBlock
//   - usage agent.UsageStats
func (_e *MockChatService_Expecter) CommitMessage(ctx interface{}, session interface{}, assistantText interface{}, sdkSessionID interface{}, isFirstMessage interface{}, blocks interface{}, usage interface{}) *MockChatService_CommitMessage_Call {
	return &MockChatService_CommitMessage_Call{Call: _e.mock.On("CommitMessage", ctx, session, assistantText, sdkSessionID, isFirstMessage, blocks, usage)}
}

func (_c *MockChatService_CommitMessage_Call) Run(run func(ctx context.Context, session *storage.ChatSession, assistantText string, sdkSessionID string, isFirstMessage bool, blocks []storage.MessageBlock, usage agent.UsageStats)) *MockChatService_CommitMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storage.ChatSession), args[2].(string), args[3].(string), args[4].(bool), args[5].([]storage.MessageBlock), args[6].(agent.UsageStats))
	})
	return _c
}

func (_c *MockChatService_CommitMessage_Call) Return(_a0 error) *MockChatService_CommitMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatService_CommitMessage_Call) RunAndReturn(run func(context.Context, *storage.ChatSession, string, string, bool, []storage.MessageBlock, agent.UsageStats) error) *MockChatService_CommitMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: ctx, agentSlug, workingDir, model, settingsProfileID
func (_m *MockChatService) CreateSession(ctx context.Context, agentSlug string, workingDir string, model string, settingsProfileID string) (*storage.ChatSession, error) {
	ret := _m.Called(ctx, agentSlug, workingDir, model, settingsProfileID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *storage.ChatSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*storage.ChatSession, error)); ok {
		return rf(ctx, agentSlug, workingDir, model, settingsProfileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *storage.ChatSession); ok {
		r0 = rf(ctx, agentSlug, workingDir, model, settingsProfileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ChatSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, agentSlug, workingDir, model, settingsProfileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockChatService_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - agentSlug string
//   - workingDir string
//   - model string
//   - settingsProfileID string
func (_e *MockChatService_Expecter) CreateSession(ctx interface{}, agentSlug interface{}, workingDir interface{}, model interface{}, settingsProfileID interface{}) *MockChatService_CreateSession_Call {
	return &MockChatService_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, agentSlug, workingDir, model, settingsProfileID)}
}

func (_c *MockChatService_CreateSession_Call) Run(run func(ctx context.Context, agentSlug string, workingDir string, model string, settingsProfileID string)) *MockChatService_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockChatService_CreateSession_Call) Return(_a0 *storage.ChatSession, _a1 error) *MockChatService_CreateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_CreateSession_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*storage.ChatSession, error)) *MockChatService_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function with given fields: ctx, id
func (_m *MockChatService) DeleteSession(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatService_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockChatService_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockChatService_Expecter) DeleteSession(ctx interface{}, id interface{}) *MockChatService_DeleteSession_Call {
	return &MockChatService_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, id)}
}

func (_c *MockChatService_DeleteSession_Call) Run(run func(ctx context.Context, id string)) *MockChatService_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockChatService_DeleteSession_Call) Return(_a0 error) *MockChatService_DeleteSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatService_DeleteSession_Call) RunAndReturn(run func(context.Context, string) error) *MockChatService_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, id
func (_m *MockChatService) GetSession(ctx context.Context, id string) (*storage.ChatSession, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *storage.ChatSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.ChatSession, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.ChatSession); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ChatSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockChatService_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockChatService_Expecter) GetSession(ctx interface{}, id interface{}) *MockChatService_GetSession_Call {
	return &MockChatService_GetSession_Call{Call: _e.mock.On("GetSession", ctx, id)}
}

func (_c *MockChatService_GetSession_Call) Run(run func(ctx context.Context, id string)) *MockChatService_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockChatService_GetSession_Call) Return(_a0 *storage.ChatSession, _a1 error) *MockChatService_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_GetSession_Call) RunAndReturn(run func(context.Context, string) (*storage.ChatSession, error)) *MockChatService_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionWithMessages provides a mock function with given fields: ctx, id
func (_m *MockChatService) GetSessionWithMessages(ctx context.Context, id string) (*storage.ChatSession, []storage.ChatMessage, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionWithMessages")
	}

	var r0 *storage.ChatSession
	var r1 []storage.ChatMessage
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.ChatSession, []storage.ChatMessage, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.ChatSession); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ChatSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) []storage.ChatMessage); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]storage.ChatMessage)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockChatService_GetSessionWithMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionWithMessages'
type MockChatService_GetSessionWithMessages_Call struct {
	*mock.Call
}

// GetSessionWithMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockChatService_Expecter) GetSessionWithMessages(ctx interface{}, id interface{}) *MockChatService_GetSessionWithMessages_Call {
	return &MockChatService_GetSessionWithMessages_Call{Call: _e.mock.On("GetSessionWithMessages", ctx, id)}
}

func (_c *MockChatService_GetSessionWithMessages_Call) Run(run func(ctx context.Context, id string)) *MockChatService_GetSessionWithMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockChatService_GetSessionWithMessages_Call) Return(_a0 *storage.ChatSession, _a1 []storage.ChatMessage, _a2 error) *MockChatService_GetSessionWithMessages_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockChatService_GetSessionWithMessages_Call) RunAndReturn(run func(context.Context, string) (*storage.ChatSession, []storage.ChatMessage, error)) *MockChatService_GetSessionWithMessages_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function with given fields: ctx
func (_m *MockChatService) ListSessions(ctx context.Context) ([]*storage.ChatSession, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []*storage.ChatSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*storage.ChatSession, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*storage.ChatSession); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.ChatSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockChatService_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChatService_Expecter) ListSessions(ctx interface{}) *MockChatService_ListSessions_Call {
	return &MockChatService_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx)}
}

func (_c *MockChatService_ListSessions_Call) Run(run func(ctx context.Context)) *MockChatService_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockChatService_ListSessions_Call) Return(_a0 []*storage.ChatSession, _a1 error) *MockChatService_ListSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_ListSessions_Call) RunAndReturn(run func(context.Context) ([]*storage.ChatSession, error)) *MockChatService_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSession provides a mock function with given fields: ctx, session
func (_m *MockChatService) UpdateSession(ctx context.Context, session *storage.ChatSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.ChatSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatService_UpdateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSession'
type MockChatService_UpdateSession_Call struct {
	*mock.Call
}

// UpdateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *storage.ChatSession
func (_e *MockChatService_Expecter) UpdateSession(ctx interface{}, session interface{}) *MockChatService_UpdateSession_Call {
	return &MockChatService_UpdateSession_Call{Call: _e.mock.On("UpdateSession", ctx, session)}
}

func (_c *MockChatService_UpdateSession_Call) Run(run func(ctx context.Context, session *storage.ChatSession)) *MockChatService_UpdateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storage.ChatSession))
	})
	return _c
}

func (_c *MockChatService_UpdateSession_Call) Return(_a0 error) *MockChatService_UpdateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatService_UpdateSession_Call) RunAndReturn(run func(context.Context, *storage.ChatSession) error) *MockChatService_UpdateSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatService creates a new instance of MockChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatService {
	mock := &MockChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
