// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	config "github.com/shaharia-lab/agento/internal/config"

	mock "github.com/stretchr/testify/mock"
)

// MockAgentService is an autogenerated mock type for the AgentService type
type MockAgentService struct {
	mock.Mock
}

type MockAgentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentService) EXPECT() *MockAgentService_Expecter {
	return &MockAgentService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, agent
func (_m *MockAgentService) Create(ctx context.Context, agent *config.AgentConfig) (*config.AgentConfig, error) {
	ret := _m.Called(ctx, agent)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *config.AgentConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *config.AgentConfig) (*config.AgentConfig, error)); ok {
		return rf(ctx, agent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *config.AgentConfig) *config.AgentConfig); ok {
		r0 = rf(ctx, agent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.AgentConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *config.AgentConfig) error); ok {
		r1 = rf(ctx, agent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAgentService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - agent *config.AgentConfig
func (_e *MockAgentService_Expecter) Create(ctx interface{}, agent interface{}) *MockAgentService_Create_Call {
	return &MockAgentService_Create_Call{Call: _e.mock.On("Create", ctx, agent)}
}

func (_c *MockAgentService_Create_Call) Run(run func(ctx context.Context, agent *config.AgentConfig)) *MockAgentService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*config.AgentConfig))
	})
	return _c
}

func (_c *MockAgentService_Create_Call) Return(_a0 *config.AgentConfig, _a1 error) *MockAgentService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentService_Create_Call) RunAndReturn(run func(context.Context, *config.AgentConfig) (*config.AgentConfig, error)) *MockAgentService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, slug
func (_m *MockAgentService) Delete(ctx context.Context, slug string) error {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAgentService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockAgentService_Expecter) Delete(ctx interface{}, slug interface{}) *MockAgentService_Delete_Call {
	return &MockAgentService_Delete_Call{Call: _e.mock.On("Delete", ctx, slug)}
}

func (_c *MockAgentService_Delete_Call) Run(run func(ctx context.Context, slug string)) *MockAgentService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAgentService_Delete_Call) Return(_a0 error) *MockAgentService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockAgentService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, slug
func (_m *MockAgentService) Get(ctx context.Context, slug string) (*config.AgentConfig, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *config.AgentConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*config.AgentConfig, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *config.AgentConfig); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.AgentConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAgentService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockAgentService_Expecter) Get(ctx interface{}, slug interface{}) *MockAgentService_Get_Call {
	return &MockAgentService_Get_Call{Call: _e.mock.On("Get", ctx, slug)}
}

func (_c *MockAgentService_Get_Call) Run(run func(ctx context.Context, slug string)) *MockAgentService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAgentService_Get_Call) Return(_a0 *config.AgentConfig, _a1 error) *MockAgentService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentService_Get_Call) RunAndReturn(run func(context.Context, string) (*config.AgentConfig, error)) *MockAgentService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockAgentService) List(ctx context.Context) ([]*config.AgentConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*config.AgentConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*config.AgentConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*config.AgentConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*config.AgentConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAgentService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgentService_Expecter) List(ctx interface{}) *MockAgentService_List_Call {
	return &MockAgentService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockAgentService_List_Call) Run(run func(ctx context.Context)) *MockAgentService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAgentService_List_Call) Return(_a0 []*config.AgentConfig, _a1 error) *MockAgentService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentService_List_Call) RunAndReturn(run func(context.Context) ([]*config.AgentConfig, error)) *MockAgentService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, slug, agent
func (_m *MockAgentService) Update(ctx context.Context, slug string, agent *config.AgentConfig) (*config.AgentConfig, error) {
	ret := _m.Called(ctx, slug, agent)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *config.AgentConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *config.AgentConfig) (*config.AgentConfig, error)); ok {
		return rf(ctx, slug, agent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *config.AgentConfig) *config.AgentConfig); ok {
		r0 = rf(ctx, slug, agent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.AgentConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *config.AgentConfig) error); ok {
		r1 = rf(ctx, slug, agent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAgentService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - agent *config.AgentConfig
func (_e *MockAgentService_Expecter) Update(ctx interface{}, slug interface{}, agent interface{}) *MockAgentService_Update_Call {
	return &MockAgentService_Update_Call{Call: _e.mock.On("Update", ctx, slug, agent)}
}

func (_c *MockAgentService_Update_Call) Run(run func(ctx context.Context, slug string, agent *config.AgentConfig)) *MockAgentService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*config.AgentConfig))
	})
	return _c
}

func (_c *MockAgentService_Update_Call) Return(_a0 *config.AgentConfig, _a1 error) *MockAgentService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentService_Update_Call) RunAndReturn(run func(context.Context, string, *config.AgentConfig) (*config.AgentConfig, error)) *MockAgentService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentService creates a new instance of MockAgentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentService {
	mock := &MockAgentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
