// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/shaharia-lab/agento/internal/storage"
)

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// BulkDeleteJobHistory provides a mock function with given fields: ctx, ids
func (_m *MockTaskService) BulkDeleteJobHistory(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDeleteJobHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_BulkDeleteJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDeleteJobHistory'
type MockTaskService_BulkDeleteJobHistory_Call struct {
	*mock.Call
}

// BulkDeleteJobHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockTaskService_Expecter) BulkDeleteJobHistory(ctx interface{}, ids interface{}) *MockTaskService_BulkDeleteJobHistory_Call {
	return &MockTaskService_BulkDeleteJobHistory_Call{Call: _e.mock.On("BulkDeleteJobHistory", ctx, ids)}
}

func (_c *MockTaskService_BulkDeleteJobHistory_Call) Run(run func(ctx context.Context, ids []string)) *MockTaskService_BulkDeleteJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockTaskService_BulkDeleteJobHistory_Call) Return(_a0 error) *MockTaskService_BulkDeleteJobHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_BulkDeleteJobHistory_Call) RunAndReturn(run func(context.Context, []string) error) *MockTaskService_BulkDeleteJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *MockTaskService) CreateTask(ctx context.Context, task *storage.ScheduledTask) (*storage.ScheduledTask, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *storage.ScheduledTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.ScheduledTask) (*storage.ScheduledTask, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *storage.ScheduledTask) *storage.ScheduledTask); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ScheduledTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *storage.ScheduledTask) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskService_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *storage.ScheduledTask
func (_e *MockTaskService_Expecter) CreateTask(ctx interface{}, task interface{}) *MockTaskService_CreateTask_Call {
	return &MockTaskService_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task)}
}

func (_c *MockTaskService_CreateTask_Call) Run(run func(ctx context.Context, task *storage.ScheduledTask)) *MockTaskService_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storage.ScheduledTask))
	})
	return _c
}

func (_c *MockTaskService_CreateTask_Call) Return(_a0 *storage.ScheduledTask, _a1 error) *MockTaskService_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_CreateTask_Call) RunAndReturn(run func(context.Context, *storage.ScheduledTask) (*storage.ScheduledTask, error)) *MockTaskService_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJobHistory provides a mock function with given fields: ctx, id
func (_m *MockTaskService) DeleteJobHistory(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJobHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_DeleteJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJobHistory'
type MockTaskService_DeleteJobHistory_Call struct {
	*mock.Call
}

// DeleteJobHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskService_Expecter) DeleteJobHistory(ctx interface{}, id interface{}) *MockTaskService_DeleteJobHistory_Call {
	return &MockTaskService_DeleteJobHistory_Call{Call: _e.mock.On("DeleteJobHistory", ctx, id)}
}

func (_c *MockTaskService_DeleteJobHistory_Call) Run(run func(ctx context.Context, id string)) *MockTaskService_DeleteJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_DeleteJobHistory_Call) Return(_a0 error) *MockTaskService_DeleteJobHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_DeleteJobHistory_Call) RunAndReturn(run func(context.Context, string) error) *MockTaskService_DeleteJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function with given fields: ctx, id
func (_m *MockTaskService) DeleteTask(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockTaskService_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskService_Expecter) DeleteTask(ctx interface{}, id interface{}) *MockTaskService_DeleteTask_Call {
	return &MockTaskService_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, id)}
}

func (_c *MockTaskService_DeleteTask_Call) Run(run func(ctx context.Context, id string)) *MockTaskService_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_DeleteTask_Call) Return(_a0 error) *MockTaskService_DeleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_DeleteTask_Call) RunAndReturn(run func(context.Context, string) error) *MockTaskService_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobHistory provides a mock function with given fields: ctx, id
func (_m *MockTaskService) GetJobHistory(ctx context.Context, id string) (*storage.JobHistory, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetJobHistory")
	}

	var r0 *storage.JobHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.JobHistory, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.JobHistory); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.JobHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_GetJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobHistory'
type MockTaskService_GetJobHistory_Call struct {
	*mock.Call
}

// GetJobHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskService_Expecter) GetJobHistory(ctx interface{}, id interface{}) *MockTaskService_GetJobHistory_Call {
	return &MockTaskService_GetJobHistory_Call{Call: _e.mock.On("GetJobHistory", ctx, id)}
}

func (_c *MockTaskService_GetJobHistory_Call) Run(run func(ctx context.Context, id string)) *MockTaskService_GetJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_GetJobHistory_Call) Return(_a0 *storage.JobHistory, _a1 error) *MockTaskService_GetJobHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_GetJobHistory_Call) RunAndReturn(run func(context.Context, string) (*storage.JobHistory, error)) *MockTaskService_GetJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: ctx, id
func (_m *MockTaskService) GetTask(ctx context.Context, id string) (*storage.ScheduledTask, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *storage.ScheduledTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.ScheduledTask, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.ScheduledTask); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ScheduledTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockTaskService_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskService_Expecter) GetTask(ctx interface{}, id interface{}) *MockTaskService_GetTask_Call {
	return &MockTaskService_GetTask_Call{Call: _e.mock.On("GetTask", ctx, id)}
}

func (_c *MockTaskService_GetTask_Call) Run(run func(ctx context.Context, id string)) *MockTaskService_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_GetTask_Call) Return(_a0 *storage.ScheduledTask, _a1 error) *MockTaskService_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_GetTask_Call) RunAndReturn(run func(context.Context, string) (*storage.ScheduledTask, error)) *MockTaskService_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllJobHistory provides a mock function with given fields: ctx, limit, offset
func (_m *MockTaskService) ListAllJobHistory(ctx context.Context, limit int, offset int) ([]*storage.JobHistory, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAllJobHistory")
	}

	var r0 []*storage.JobHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*storage.JobHistory, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*storage.JobHistory); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.JobHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_ListAllJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllJobHistory'
type MockTaskService_ListAllJobHistory_Call struct {
	*mock.Call
}

// ListAllJobHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockTaskService_Expecter) ListAllJobHistory(ctx interface{}, limit interface{}, offset interface{}) *MockTaskService_ListAllJobHistory_Call {
	return &MockTaskService_ListAllJobHistory_Call{Call: _e.mock.On("ListAllJobHistory", ctx, limit, offset)}
}

func (_c *MockTaskService_ListAllJobHistory_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockTaskService_ListAllJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTaskService_ListAllJobHistory_Call) Return(_a0 []*storage.JobHistory, _a1 error) *MockTaskService_ListAllJobHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_ListAllJobHistory_Call) RunAndReturn(run func(context.Context, int, int) ([]*storage.JobHistory, error)) *MockTaskService_ListAllJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListJobHistory provides a mock function with given fields: ctx, taskID, limit
func (_m *MockTaskService) ListJobHistory(ctx context.Context, taskID string, limit int) ([]*storage.JobHistory, error) {
	ret := _m.Called(ctx, taskID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListJobHistory")
	}

	var r0 []*storage.JobHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]*storage.JobHistory, error)); ok {
		return rf(ctx, taskID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*storage.JobHistory); ok {
		r0 = rf(ctx, taskID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.JobHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, taskID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_ListJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJobHistory'
type MockTaskService_ListJobHistory_Call struct {
	*mock.Call
}

// ListJobHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - limit int
func (_e *MockTaskService_Expecter) ListJobHistory(ctx interface{}, taskID interface{}, limit interface{}) *MockTaskService_ListJobHistory_Call {
	return &MockTaskService_ListJobHistory_Call{Call: _e.mock.On("ListJobHistory", ctx, taskID, limit)}
}

func (_c *MockTaskService_ListJobHistory_Call) Run(run func(ctx context.Context, taskID string, limit int)) *MockTaskService_ListJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockTaskService_ListJobHistory_Call) Return(_a0 []*storage.JobHistory, _a1 error) *MockTaskService_ListJobHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_ListJobHistory_Call) RunAndReturn(run func(context.Context, string, int) ([]*storage.JobHistory, error)) *MockTaskService_ListJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with given fields: ctx
func (_m *MockTaskService) ListTasks(ctx context.Context) ([]*storage.ScheduledTask, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []*storage.ScheduledTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*storage.ScheduledTask, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*storage.ScheduledTask); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.ScheduledTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockTaskService_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskService_Expecter) ListTasks(ctx interface{}) *MockTaskService_ListTasks_Call {
	return &MockTaskService_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx)}
}

func (_c *MockTaskService_ListTasks_Call) Run(run func(ctx context.Context)) *MockTaskService_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskService_ListTasks_Call) Return(_a0 []*storage.ScheduledTask, _a1 error) *MockTaskService_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_ListTasks_Call) RunAndReturn(run func(context.Context) ([]*storage.ScheduledTask, error)) *MockTaskService_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// PauseTask provides a mock function with given fields: ctx, id
func (_m *MockTaskService) PauseTask(ctx context.Context, id string) (*storage.ScheduledTask, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PauseTask")
	}

	var r0 *storage.ScheduledTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.ScheduledTask, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.ScheduledTask); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ScheduledTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_PauseTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseTask'
type MockTaskService_PauseTask_Call struct {
	*mock.Call
}

// PauseTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskService_Expecter) PauseTask(ctx interface{}, id interface{}) *MockTaskService_PauseTask_Call {
	return &MockTaskService_PauseTask_Call{Call: _e.mock.On("PauseTask", ctx, id)}
}

func (_c *MockTaskService_PauseTask_Call) Run(run func(ctx context.Context, id string)) *MockTaskService_PauseTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_PauseTask_Call) Return(_a0 *storage.ScheduledTask, _a1 error) *MockTaskService_PauseTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_PauseTask_Call) RunAndReturn(run func(context.Context, string) (*storage.ScheduledTask, error)) *MockTaskService_PauseTask_Call {
	_c.Call.Return(run)
	return _c
}

// ResumeTask provides a mock function with given fields: ctx, id
func (_m *MockTaskService) ResumeTask(ctx context.Context, id string) (*storage.ScheduledTask, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ResumeTask")
	}

	var r0 *storage.ScheduledTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.ScheduledTask, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.ScheduledTask); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ScheduledTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_ResumeTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumeTask'
type MockTaskService_ResumeTask_Call struct {
	*mock.Call
}

// ResumeTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskService_Expecter) ResumeTask(ctx interface{}, id interface{}) *MockTaskService_ResumeTask_Call {
	return &MockTaskService_ResumeTask_Call{Call: _e.mock.On("ResumeTask", ctx, id)}
}

func (_c *MockTaskService_ResumeTask_Call) Run(run func(ctx context.Context, id string)) *MockTaskService_ResumeTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_ResumeTask_Call) Return(_a0 *storage.ScheduledTask, _a1 error) *MockTaskService_ResumeTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_ResumeTask_Call) RunAndReturn(run func(context.Context, string) (*storage.ScheduledTask, error)) *MockTaskService_ResumeTask_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: ctx, id, task
func (_m *MockTaskService) UpdateTask(ctx context.Context, id string, task *storage.ScheduledTask) (*storage.ScheduledTask, error) {
	ret := _m.Called(ctx, id, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *storage.ScheduledTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *storage.ScheduledTask) (*storage.ScheduledTask, error)); ok {
		return rf(ctx, id, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *storage.ScheduledTask) *storage.ScheduledTask); ok {
		r0 = rf(ctx, id, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ScheduledTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *storage.ScheduledTask) error); ok {
		r1 = rf(ctx, id, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockTaskService_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - task *storage.ScheduledTask
func (_e *MockTaskService_Expecter) UpdateTask(ctx interface{}, id interface{}, task interface{}) *MockTaskService_UpdateTask_Call {
	return &MockTaskService_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, id, task)}
}

func (_c *MockTaskService_UpdateTask_Call) Run(run func(ctx context.Context, id string, task *storage.ScheduledTask)) *MockTaskService_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*storage.ScheduledTask))
	})
	return _c
}

func (_c *MockTaskService_UpdateTask_Call) Return(_a0 *storage.ScheduledTask, _a1 error) *MockTaskService_UpdateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_UpdateTask_Call) RunAndReturn(run func(context.Context, string, *storage.ScheduledTask) (*storage.ScheduledTask, error)) *MockTaskService_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
