// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	config "github.com/shaharia-lab/agento/internal/config"

	mock "github.com/stretchr/testify/mock"

	service "github.com/shaharia-lab/agento/internal/service"
)

// MockIntegrationService is an autogenerated mock type for the IntegrationService type
type MockIntegrationService struct {
	mock.Mock
}

type MockIntegrationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIntegrationService) EXPECT() *MockIntegrationService_Expecter {
	return &MockIntegrationService_Expecter{mock: &_m.Mock}
}

// AvailableTools provides a mock function with given fields: ctx
func (_m *MockIntegrationService) AvailableTools(ctx context.Context) ([]service.AvailableTool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AvailableTools")
	}

	var r0 []service.AvailableTool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]service.AvailableTool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []service.AvailableTool); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.AvailableTool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntegrationService_AvailableTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailableTools'
type MockIntegrationService_AvailableTools_Call struct {
	*mock.Call
}

// AvailableTools is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIntegrationService_Expecter) AvailableTools(ctx interface{}) *MockIntegrationService_AvailableTools_Call {
	return &MockIntegrationService_AvailableTools_Call{Call: _e.mock.On("AvailableTools", ctx)}
}

func (_c *MockIntegrationService_AvailableTools_Call) Run(run func(ctx context.Context)) *MockIntegrationService_AvailableTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIntegrationService_AvailableTools_Call) Return(_a0 []service.AvailableTool, _a1 error) *MockIntegrationService_AvailableTools_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIntegrationService_AvailableTools_Call) RunAndReturn(run func(context.Context) ([]service.AvailableTool, error)) *MockIntegrationService_AvailableTools_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, cfg
func (_m *MockIntegrationService) Create(ctx context.Context, cfg *config.IntegrationConfig) (*config.IntegrationConfig, error) {
	ret := _m.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *config.IntegrationConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *config.IntegrationConfig) (*config.IntegrationConfig, error)); ok {
		return rf(ctx, cfg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *config.IntegrationConfig) *config.IntegrationConfig); ok {
		r0 = rf(ctx, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.IntegrationConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *config.IntegrationConfig) error); ok {
		r1 = rf(ctx, cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntegrationService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIntegrationService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg *config.IntegrationConfig
func (_e *MockIntegrationService_Expecter) Create(ctx interface{}, cfg interface{}) *MockIntegrationService_Create_Call {
	return &MockIntegrationService_Create_Call{Call: _e.mock.On("Create", ctx, cfg)}
}

func (_c *MockIntegrationService_Create_Call) Run(run func(ctx context.Context, cfg *config.IntegrationConfig)) *MockIntegrationService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*config.IntegrationConfig))
	})
	return _c
}

func (_c *MockIntegrationService_Create_Call) Return(_a0 *config.IntegrationConfig, _a1 error) *MockIntegrationService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIntegrationService_Create_Call) RunAndReturn(run func(context.Context, *config.IntegrationConfig) (*config.IntegrationConfig, error)) *MockIntegrationService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockIntegrationService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIntegrationService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIntegrationService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIntegrationService_Expecter) Delete(ctx interface{}, id interface{}) *MockIntegrationService_Delete_Call {
	return &MockIntegrationService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIntegrationService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockIntegrationService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIntegrationService_Delete_Call) Return(_a0 error) *MockIntegrationService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntegrationService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockIntegrationService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockIntegrationService) Get(ctx context.Context, id string) (*config.IntegrationConfig, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *config.IntegrationConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*config.IntegrationConfig, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *config.IntegrationConfig); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.IntegrationConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntegrationService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIntegrationService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIntegrationService_Expecter) Get(ctx interface{}, id interface{}) *MockIntegrationService_Get_Call {
	return &MockIntegrationService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockIntegrationService_Get_Call) Run(run func(ctx context.Context, id string)) *MockIntegrationService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIntegrationService_Get_Call) Return(_a0 *config.IntegrationConfig, _a1 error) *MockIntegrationService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIntegrationService_Get_Call) RunAndReturn(run func(context.Context, string) (*config.IntegrationConfig, error)) *MockIntegrationService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthStatus provides a mock function with given fields: ctx, id
func (_m *MockIntegrationService) GetAuthStatus(ctx context.Context, id string) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthStatus")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntegrationService_GetAuthStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthStatus'
type MockIntegrationService_GetAuthStatus_Call struct {
	*mock.Call
}

// GetAuthStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIntegrationService_Expecter) GetAuthStatus(ctx interface{}, id interface{}) *MockIntegrationService_GetAuthStatus_Call {
	return &MockIntegrationService_GetAuthStatus_Call{Call: _e.mock.On("GetAuthStatus", ctx, id)}
}

func (_c *MockIntegrationService_GetAuthStatus_Call) Run(run func(ctx context.Context, id string)) *MockIntegrationService_GetAuthStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIntegrationService_GetAuthStatus_Call) Return(authenticated bool, err error) *MockIntegrationService_GetAuthStatus_Call {
	_c.Call.Return(authenticated, err)
	return _c
}

func (_c *MockIntegrationService_GetAuthStatus_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockIntegrationService_GetAuthStatus_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockIntegrationService) List(ctx context.Context) ([]*config.IntegrationConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*config.IntegrationConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*config.IntegrationConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*config.IntegrationConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*config.IntegrationConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntegrationService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIntegrationService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIntegrationService_Expecter) List(ctx interface{}) *MockIntegrationService_List_Call {
	return &MockIntegrationService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockIntegrationService_List_Call) Run(run func(ctx context.Context)) *MockIntegrationService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIntegrationService_List_Call) Return(_a0 []*config.IntegrationConfig, _a1 error) *MockIntegrationService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIntegrationService_List_Call) RunAndReturn(run func(context.Context) ([]*config.IntegrationConfig, error)) *MockIntegrationService_List_Call {
	_c.Call.Return(run)
	return _c
}

// StartOAuth provides a mock function with given fields: ctx, id
func (_m *MockIntegrationService) StartOAuth(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for StartOAuth")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntegrationService_StartOAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartOAuth'
type MockIntegrationService_StartOAuth_Call struct {
	*mock.Call
}

// StartOAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIntegrationService_Expecter) StartOAuth(ctx interface{}, id interface{}) *MockIntegrationService_StartOAuth_Call {
	return &MockIntegrationService_StartOAuth_Call{Call: _e.mock.On("StartOAuth", ctx, id)}
}

func (_c *MockIntegrationService_StartOAuth_Call) Run(run func(ctx context.Context, id string)) *MockIntegrationService_StartOAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIntegrationService_StartOAuth_Call) Return(authURL string, err error) *MockIntegrationService_StartOAuth_Call {
	_c.Call.Return(authURL, err)
	return _c
}

func (_c *MockIntegrationService_StartOAuth_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockIntegrationService_StartOAuth_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, cfg
func (_m *MockIntegrationService) Update(ctx context.Context, id string, cfg *config.IntegrationConfig) (*config.IntegrationConfig, error) {
	ret := _m.Called(ctx, id, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *config.IntegrationConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *config.IntegrationConfig) (*config.IntegrationConfig, error)); ok {
		return rf(ctx, id, cfg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *config.IntegrationConfig) *config.IntegrationConfig); ok {
		r0 = rf(ctx, id, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.IntegrationConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *config.IntegrationConfig) error); ok {
		r1 = rf(ctx, id, cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntegrationService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIntegrationService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - cfg *config.IntegrationConfig
func (_e *MockIntegrationService_Expecter) Update(ctx interface{}, id interface{}, cfg interface{}) *MockIntegrationService_Update_Call {
	return &MockIntegrationService_Update_Call{Call: _e.mock.On("Update", ctx, id, cfg)}
}

func (_c *MockIntegrationService_Update_Call) Run(run func(ctx context.Context, id string, cfg *config.IntegrationConfig)) *MockIntegrationService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*config.IntegrationConfig))
	})
	return _c
}

func (_c *MockIntegrationService_Update_Call) Return(_a0 *config.IntegrationConfig, _a1 error) *MockIntegrationService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIntegrationService_Update_Call) RunAndReturn(run func(context.Context, string, *config.IntegrationConfig) (*config.IntegrationConfig, error)) *MockIntegrationService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateTokenAuth provides a mock function with given fields: ctx, cfg
func (_m *MockIntegrationService) ValidateTokenAuth(ctx context.Context, cfg *config.IntegrationConfig) error {
	ret := _m.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for ValidateTokenAuth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *config.IntegrationConfig) error); ok {
		r0 = rf(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIntegrationService_ValidateTokenAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateTokenAuth'
type MockIntegrationService_ValidateTokenAuth_Call struct {
	*mock.Call
}

// ValidateTokenAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg *config.IntegrationConfig
func (_e *MockIntegrationService_Expecter) ValidateTokenAuth(ctx interface{}, cfg interface{}) *MockIntegrationService_ValidateTokenAuth_Call {
	return &MockIntegrationService_ValidateTokenAuth_Call{Call: _e.mock.On("ValidateTokenAuth", ctx, cfg)}
}

func (_c *MockIntegrationService_ValidateTokenAuth_Call) Run(run func(ctx context.Context, cfg *config.IntegrationConfig)) *MockIntegrationService_ValidateTokenAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*config.IntegrationConfig))
	})
	return _c
}

func (_c *MockIntegrationService_ValidateTokenAuth_Call) Return(_a0 error) *MockIntegrationService_ValidateTokenAuth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntegrationService_ValidateTokenAuth_Call) RunAndReturn(run func(context.Context, *config.IntegrationConfig) error) *MockIntegrationService_ValidateTokenAuth_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIntegrationService creates a new instance of MockIntegrationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIntegrationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIntegrationService {
	mock := &MockIntegrationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
