// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	notification "github.com/shaharia-lab/agento/internal/notification"
	mock "github.com/stretchr/testify/mock"

	storage "github.com/shaharia-lab/agento/internal/storage"
)

// MockNotificationService is an autogenerated mock type for the NotificationService type
type MockNotificationService struct {
	mock.Mock
}

type MockNotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationService) EXPECT() *MockNotificationService_Expecter {
	return &MockNotificationService_Expecter{mock: &_m.Mock}
}

// GetSettings provides a mock function with no fields
func (_m *MockNotificationService) GetSettings() (*notification.NotificationSettings, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSettings")
	}

	var r0 *notification.NotificationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func() (*notification.NotificationSettings, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *notification.NotificationSettings); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notification.NotificationSettings)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationService_GetSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSettings'
type MockNotificationService_GetSettings_Call struct {
	*mock.Call
}

// GetSettings is a helper method to define mock.On call
func (_e *MockNotificationService_Expecter) GetSettings() *MockNotificationService_GetSettings_Call {
	return &MockNotificationService_GetSettings_Call{Call: _e.mock.On("GetSettings")}
}

func (_c *MockNotificationService_GetSettings_Call) Run(run func()) *MockNotificationService_GetSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotificationService_GetSettings_Call) Return(_a0 *notification.NotificationSettings, _a1 error) *MockNotificationService_GetSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationService_GetSettings_Call) RunAndReturn(run func() (*notification.NotificationSettings, error)) *MockNotificationService_GetSettings_Call {
	_c.Call.Return(run)
	return _c
}

// ListLog provides a mock function with given fields: ctx, limit
func (_m *MockNotificationService) ListLog(ctx context.Context, limit int) ([]storage.NotificationLogEntry, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListLog")
	}

	var r0 []storage.NotificationLogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]storage.NotificationLogEntry, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []storage.NotificationLogEntry); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.NotificationLogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationService_ListLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLog'
type MockNotificationService_ListLog_Call struct {
	*mock.Call
}

// ListLog is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockNotificationService_Expecter) ListLog(ctx interface{}, limit interface{}) *MockNotificationService_ListLog_Call {
	return &MockNotificationService_ListLog_Call{Call: _e.mock.On("ListLog", ctx, limit)}
}

func (_c *MockNotificationService_ListLog_Call) Run(run func(ctx context.Context, limit int)) *MockNotificationService_ListLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockNotificationService_ListLog_Call) Return(_a0 []storage.NotificationLogEntry, _a1 error) *MockNotificationService_ListLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationService_ListLog_Call) RunAndReturn(run func(context.Context, int) ([]storage.NotificationLogEntry, error)) *MockNotificationService_ListLog_Call {
	_c.Call.Return(run)
	return _c
}

// TestNotification provides a mock function with given fields: ctx
func (_m *MockNotificationService) TestNotification(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TestNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationService_TestNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestNotification'
type MockNotificationService_TestNotification_Call struct {
	*mock.Call
}

// TestNotification is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNotificationService_Expecter) TestNotification(ctx interface{}) *MockNotificationService_TestNotification_Call {
	return &MockNotificationService_TestNotification_Call{Call: _e.mock.On("TestNotification", ctx)}
}

func (_c *MockNotificationService_TestNotification_Call) Run(run func(ctx context.Context)) *MockNotificationService_TestNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockNotificationService_TestNotification_Call) Return(_a0 error) *MockNotificationService_TestNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationService_TestNotification_Call) RunAndReturn(run func(context.Context) error) *MockNotificationService_TestNotification_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSettings provides a mock function with given fields: settings
func (_m *MockNotificationService) UpdateSettings(settings *notification.NotificationSettings) error {
	ret := _m.Called(settings)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*notification.NotificationSettings) error); ok {
		r0 = rf(settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationService_UpdateSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSettings'
type MockNotificationService_UpdateSettings_Call struct {
	*mock.Call
}

// UpdateSettings is a helper method to define mock.On call
//   - settings *notification.NotificationSettings
func (_e *MockNotificationService_Expecter) UpdateSettings(settings interface{}) *MockNotificationService_UpdateSettings_Call {
	return &MockNotificationService_UpdateSettings_Call{Call: _e.mock.On("UpdateSettings", settings)}
}

func (_c *MockNotificationService_UpdateSettings_Call) Run(run func(settings *notification.NotificationSettings)) *MockNotificationService_UpdateSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*notification.NotificationSettings))
	})
	return _c
}

func (_c *MockNotificationService_UpdateSettings_Call) Return(_a0 error) *MockNotificationService_UpdateSettings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationService_UpdateSettings_Call) RunAndReturn(run func(*notification.NotificationSettings) error) *MockNotificationService_UpdateSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationService creates a new instance of MockNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationService {
	mock := &MockNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
