// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	config "github.com/shaharia-lab/agento/internal/config"

	mock "github.com/stretchr/testify/mock"
)

// MockAgentStore is an autogenerated mock type for the AgentStore type
type MockAgentStore struct {
	mock.Mock
}

type MockAgentStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentStore) EXPECT() *MockAgentStore_Expecter {
	return &MockAgentStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, slug
func (_m *MockAgentStore) Delete(ctx context.Context, slug string) error {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAgentStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockAgentStore_Expecter) Delete(ctx interface{}, slug interface{}) *MockAgentStore_Delete_Call {
	return &MockAgentStore_Delete_Call{Call: _e.mock.On("Delete", ctx, slug)}
}

func (_c *MockAgentStore_Delete_Call) Run(run func(ctx context.Context, slug string)) *MockAgentStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAgentStore_Delete_Call) Return(_a0 error) *MockAgentStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockAgentStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, slug
func (_m *MockAgentStore) Get(ctx context.Context, slug string) (*config.AgentConfig, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *config.AgentConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*config.AgentConfig, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *config.AgentConfig); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.AgentConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAgentStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockAgentStore_Expecter) Get(ctx interface{}, slug interface{}) *MockAgentStore_Get_Call {
	return &MockAgentStore_Get_Call{Call: _e.mock.On("Get", ctx, slug)}
}

func (_c *MockAgentStore_Get_Call) Run(run func(ctx context.Context, slug string)) *MockAgentStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAgentStore_Get_Call) Return(_a0 *config.AgentConfig, _a1 error) *MockAgentStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentStore_Get_Call) RunAndReturn(run func(context.Context, string) (*config.AgentConfig, error)) *MockAgentStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockAgentStore) List(ctx context.Context) ([]*config.AgentConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*config.AgentConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*config.AgentConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*config.AgentConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*config.AgentConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAgentStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgentStore_Expecter) List(ctx interface{}) *MockAgentStore_List_Call {
	return &MockAgentStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockAgentStore_List_Call) Run(run func(ctx context.Context)) *MockAgentStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAgentStore_List_Call) Return(_a0 []*config.AgentConfig, _a1 error) *MockAgentStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentStore_List_Call) RunAndReturn(run func(context.Context) ([]*config.AgentConfig, error)) *MockAgentStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, agent
func (_m *MockAgentStore) Save(ctx context.Context, agent *config.AgentConfig) error {
	ret := _m.Called(ctx, agent)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *config.AgentConfig) error); ok {
		r0 = rf(ctx, agent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAgentStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - agent *config.AgentConfig
func (_e *MockAgentStore_Expecter) Save(ctx interface{}, agent interface{}) *MockAgentStore_Save_Call {
	return &MockAgentStore_Save_Call{Call: _e.mock.On("Save", ctx, agent)}
}

func (_c *MockAgentStore_Save_Call) Run(run func(ctx context.Context, agent *config.AgentConfig)) *MockAgentStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*config.AgentConfig))
	})
	return _c
}

func (_c *MockAgentStore_Save_Call) Return(_a0 error) *MockAgentStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentStore_Save_Call) RunAndReturn(run func(context.Context, *config.AgentConfig) error) *MockAgentStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentStore creates a new instance of MockAgentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentStore {
	mock := &MockAgentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
