// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	storage "github.com/shaharia-lab/agento/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// MockChatStore is an autogenerated mock type for the ChatStore type
type MockChatStore struct {
	mock.Mock
}

type MockChatStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatStore) EXPECT() *MockChatStore_Expecter {
	return &MockChatStore_Expecter{mock: &_m.Mock}
}

// AppendMessage provides a mock function with given fields: ctx, sessionID, msg
func (_m *MockChatStore) AppendMessage(ctx context.Context, sessionID string, msg storage.ChatMessage) error {
	ret := _m.Called(ctx, sessionID, msg)

	if len(ret) == 0 {
		panic("no return value specified for AppendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, storage.ChatMessage) error); ok {
		r0 = rf(ctx, sessionID, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatStore_AppendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendMessage'
type MockChatStore_AppendMessage_Call struct {
	*mock.Call
}

// AppendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - msg storage.ChatMessage
func (_e *MockChatStore_Expecter) AppendMessage(ctx interface{}, sessionID interface{}, msg interface{}) *MockChatStore_AppendMessage_Call {
	return &MockChatStore_AppendMessage_Call{Call: _e.mock.On("AppendMessage", ctx, sessionID, msg)}
}

func (_c *MockChatStore_AppendMessage_Call) Run(run func(ctx context.Context, sessionID string, msg storage.ChatMessage)) *MockChatStore_AppendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(storage.ChatMessage))
	})
	return _c
}

func (_c *MockChatStore_AppendMessage_Call) Return(_a0 error) *MockChatStore_AppendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatStore_AppendMessage_Call) RunAndReturn(run func(context.Context, string, storage.ChatMessage) error) *MockChatStore_AppendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// BulkDeleteSessions provides a mock function with given fields: ctx, ids
func (_m *MockChatStore) BulkDeleteSessions(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDeleteSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatStore_BulkDeleteSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDeleteSessions'
type MockChatStore_BulkDeleteSessions_Call struct {
	*mock.Call
}

// BulkDeleteSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockChatStore_Expecter) BulkDeleteSessions(ctx interface{}, ids interface{}) *MockChatStore_BulkDeleteSessions_Call {
	return &MockChatStore_BulkDeleteSessions_Call{Call: _e.mock.On("BulkDeleteSessions", ctx, ids)}
}

func (_c *MockChatStore_BulkDeleteSessions_Call) Run(run func(ctx context.Context, ids []string)) *MockChatStore_BulkDeleteSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockChatStore_BulkDeleteSessions_Call) Return(_a0 error) *MockChatStore_BulkDeleteSessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatStore_BulkDeleteSessions_Call) RunAndReturn(run func(context.Context, []string) error) *MockChatStore_BulkDeleteSessions_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: ctx, agentSlug, workingDir, model, settingsProfileID
func (_m *MockChatStore) CreateSession(ctx context.Context, agentSlug string, workingDir string, model string, settingsProfileID string) (*storage.ChatSession, error) {
	ret := _m.Called(ctx, agentSlug, workingDir, model, settingsProfileID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *storage.ChatSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*storage.ChatSession, error)); ok {
		return rf(ctx, agentSlug, workingDir, model, settingsProfileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *storage.ChatSession); ok {
		r0 = rf(ctx, agentSlug, workingDir, model, settingsProfileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ChatSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, agentSlug, workingDir, model, settingsProfileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatStore_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockChatStore_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - agentSlug string
//   - workingDir string
//   - model string
//   - settingsProfileID string
func (_e *MockChatStore_Expecter) CreateSession(ctx interface{}, agentSlug interface{}, workingDir interface{}, model interface{}, settingsProfileID interface{}) *MockChatStore_CreateSession_Call {
	return &MockChatStore_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, agentSlug, workingDir, model, settingsProfileID)}
}

func (_c *MockChatStore_CreateSession_Call) Run(run func(ctx context.Context, agentSlug string, workingDir string, model string, settingsProfileID string)) *MockChatStore_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockChatStore_CreateSession_Call) Return(_a0 *storage.ChatSession, _a1 error) *MockChatStore_CreateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatStore_CreateSession_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*storage.ChatSession, error)) *MockChatStore_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function with given fields: ctx, id
func (_m *MockChatStore) DeleteSession(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatStore_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockChatStore_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockChatStore_Expecter) DeleteSession(ctx interface{}, id interface{}) *MockChatStore_DeleteSession_Call {
	return &MockChatStore_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, id)}
}

func (_c *MockChatStore_DeleteSession_Call) Run(run func(ctx context.Context, id string)) *MockChatStore_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockChatStore_DeleteSession_Call) Return(_a0 error) *MockChatStore_DeleteSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatStore_DeleteSession_Call) RunAndReturn(run func(context.Context, string) error) *MockChatStore_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, id
func (_m *MockChatStore) GetSession(ctx context.Context, id string) (*storage.ChatSession, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *storage.ChatSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.ChatSession, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.ChatSession); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ChatSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatStore_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockChatStore_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockChatStore_Expecter) GetSession(ctx interface{}, id interface{}) *MockChatStore_GetSession_Call {
	return &MockChatStore_GetSession_Call{Call: _e.mock.On("GetSession", ctx, id)}
}

func (_c *MockChatStore_GetSession_Call) Run(run func(ctx context.Context, id string)) *MockChatStore_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockChatStore_GetSession_Call) Return(_a0 *storage.ChatSession, _a1 error) *MockChatStore_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatStore_GetSession_Call) RunAndReturn(run func(context.Context, string) (*storage.ChatSession, error)) *MockChatStore_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionWithMessages provides a mock function with given fields: ctx, id
func (_m *MockChatStore) GetSessionWithMessages(ctx context.Context, id string) (*storage.ChatSession, []storage.ChatMessage, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionWithMessages")
	}

	var r0 *storage.ChatSession
	var r1 []storage.ChatMessage
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.ChatSession, []storage.ChatMessage, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.ChatSession); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ChatSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) []storage.ChatMessage); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]storage.ChatMessage)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockChatStore_GetSessionWithMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionWithMessages'
type MockChatStore_GetSessionWithMessages_Call struct {
	*mock.Call
}

// GetSessionWithMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockChatStore_Expecter) GetSessionWithMessages(ctx interface{}, id interface{}) *MockChatStore_GetSessionWithMessages_Call {
	return &MockChatStore_GetSessionWithMessages_Call{Call: _e.mock.On("GetSessionWithMessages", ctx, id)}
}

func (_c *MockChatStore_GetSessionWithMessages_Call) Run(run func(ctx context.Context, id string)) *MockChatStore_GetSessionWithMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockChatStore_GetSessionWithMessages_Call) Return(_a0 *storage.ChatSession, _a1 []storage.ChatMessage, _a2 error) *MockChatStore_GetSessionWithMessages_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockChatStore_GetSessionWithMessages_Call) RunAndReturn(run func(context.Context, string) (*storage.ChatSession, []storage.ChatMessage, error)) *MockChatStore_GetSessionWithMessages_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function with given fields: ctx
func (_m *MockChatStore) ListSessions(ctx context.Context) ([]*storage.ChatSession, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []*storage.ChatSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*storage.ChatSession, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*storage.ChatSession); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.ChatSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatStore_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockChatStore_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChatStore_Expecter) ListSessions(ctx interface{}) *MockChatStore_ListSessions_Call {
	return &MockChatStore_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx)}
}

func (_c *MockChatStore_ListSessions_Call) Run(run func(ctx context.Context)) *MockChatStore_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockChatStore_ListSessions_Call) Return(_a0 []*storage.ChatSession, _a1 error) *MockChatStore_ListSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatStore_ListSessions_Call) RunAndReturn(run func(context.Context) ([]*storage.ChatSession, error)) *MockChatStore_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSession provides a mock function with given fields: ctx, session
func (_m *MockChatStore) UpdateSession(ctx context.Context, session *storage.ChatSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.ChatSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatStore_UpdateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSession'
type MockChatStore_UpdateSession_Call struct {
	*mock.Call
}

// UpdateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *storage.ChatSession
func (_e *MockChatStore_Expecter) UpdateSession(ctx interface{}, session interface{}) *MockChatStore_UpdateSession_Call {
	return &MockChatStore_UpdateSession_Call{Call: _e.mock.On("UpdateSession", ctx, session)}
}

func (_c *MockChatStore_UpdateSession_Call) Run(run func(ctx context.Context, session *storage.ChatSession)) *MockChatStore_UpdateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storage.ChatSession))
	})
	return _c
}

func (_c *MockChatStore_UpdateSession_Call) Return(_a0 error) *MockChatStore_UpdateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatStore_UpdateSession_Call) RunAndReturn(run func(context.Context, *storage.ChatSession) error) *MockChatStore_UpdateSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatStore creates a new instance of MockChatStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatStore {
	mock := &MockChatStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
