// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	config "github.com/shaharia-lab/agento/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// MockIntegrationStore is an autogenerated mock type for the IntegrationStore type
type MockIntegrationStore struct {
	mock.Mock
}

type MockIntegrationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIntegrationStore) EXPECT() *MockIntegrationStore_Expecter {
	return &MockIntegrationStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: id
func (_m *MockIntegrationStore) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIntegrationStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIntegrationStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockIntegrationStore_Expecter) Delete(id interface{}) *MockIntegrationStore_Delete_Call {
	return &MockIntegrationStore_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockIntegrationStore_Delete_Call) Run(run func(id string)) *MockIntegrationStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIntegrationStore_Delete_Call) Return(_a0 error) *MockIntegrationStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntegrationStore_Delete_Call) RunAndReturn(run func(string) error) *MockIntegrationStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *MockIntegrationStore) Get(id string) (*config.IntegrationConfig, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *config.IntegrationConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*config.IntegrationConfig, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *config.IntegrationConfig); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.IntegrationConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntegrationStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIntegrationStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockIntegrationStore_Expecter) Get(id interface{}) *MockIntegrationStore_Get_Call {
	return &MockIntegrationStore_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockIntegrationStore_Get_Call) Run(run func(id string)) *MockIntegrationStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIntegrationStore_Get_Call) Return(_a0 *config.IntegrationConfig, _a1 error) *MockIntegrationStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIntegrationStore_Get_Call) RunAndReturn(run func(string) (*config.IntegrationConfig, error)) *MockIntegrationStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with no fields
func (_m *MockIntegrationStore) List() ([]*config.IntegrationConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*config.IntegrationConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*config.IntegrationConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*config.IntegrationConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*config.IntegrationConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntegrationStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIntegrationStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockIntegrationStore_Expecter) List() *MockIntegrationStore_List_Call {
	return &MockIntegrationStore_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockIntegrationStore_List_Call) Run(run func()) *MockIntegrationStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIntegrationStore_List_Call) Return(_a0 []*config.IntegrationConfig, _a1 error) *MockIntegrationStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIntegrationStore_List_Call) RunAndReturn(run func() ([]*config.IntegrationConfig, error)) *MockIntegrationStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: cfg
func (_m *MockIntegrationStore) Save(cfg *config.IntegrationConfig) error {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.IntegrationConfig) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIntegrationStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIntegrationStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - cfg *config.IntegrationConfig
func (_e *MockIntegrationStore_Expecter) Save(cfg interface{}) *MockIntegrationStore_Save_Call {
	return &MockIntegrationStore_Save_Call{Call: _e.mock.On("Save", cfg)}
}

func (_c *MockIntegrationStore_Save_Call) Run(run func(cfg *config.IntegrationConfig)) *MockIntegrationStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.IntegrationConfig))
	})
	return _c
}

func (_c *MockIntegrationStore_Save_Call) Return(_a0 error) *MockIntegrationStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntegrationStore_Save_Call) RunAndReturn(run func(*config.IntegrationConfig) error) *MockIntegrationStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIntegrationStore creates a new instance of MockIntegrationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIntegrationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIntegrationStore {
	mock := &MockIntegrationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
