// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	config "github.com/shaharia-lab/agento/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// MockAgentStore is an autogenerated mock type for the AgentStore type
type MockAgentStore struct {
	mock.Mock
}

type MockAgentStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentStore) EXPECT() *MockAgentStore_Expecter {
	return &MockAgentStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: slug
func (_m *MockAgentStore) Delete(slug string) error {
	ret := _m.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAgentStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - slug string
func (_e *MockAgentStore_Expecter) Delete(slug interface{}) *MockAgentStore_Delete_Call {
	return &MockAgentStore_Delete_Call{Call: _e.mock.On("Delete", slug)}
}

func (_c *MockAgentStore_Delete_Call) Run(run func(slug string)) *MockAgentStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAgentStore_Delete_Call) Return(_a0 error) *MockAgentStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentStore_Delete_Call) RunAndReturn(run func(string) error) *MockAgentStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: slug
func (_m *MockAgentStore) Get(slug string) (*config.AgentConfig, error) {
	ret := _m.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *config.AgentConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*config.AgentConfig, error)); ok {
		return rf(slug)
	}
	if rf, ok := ret.Get(0).(func(string) *config.AgentConfig); ok {
		r0 = rf(slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.AgentConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAgentStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - slug string
func (_e *MockAgentStore_Expecter) Get(slug interface{}) *MockAgentStore_Get_Call {
	return &MockAgentStore_Get_Call{Call: _e.mock.On("Get", slug)}
}

func (_c *MockAgentStore_Get_Call) Run(run func(slug string)) *MockAgentStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAgentStore_Get_Call) Return(_a0 *config.AgentConfig, _a1 error) *MockAgentStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentStore_Get_Call) RunAndReturn(run func(string) (*config.AgentConfig, error)) *MockAgentStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with no fields
func (_m *MockAgentStore) List() ([]*config.AgentConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*config.AgentConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*config.AgentConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*config.AgentConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*config.AgentConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAgentStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockAgentStore_Expecter) List() *MockAgentStore_List_Call {
	return &MockAgentStore_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockAgentStore_List_Call) Run(run func()) *MockAgentStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgentStore_List_Call) Return(_a0 []*config.AgentConfig, _a1 error) *MockAgentStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentStore_List_Call) RunAndReturn(run func() ([]*config.AgentConfig, error)) *MockAgentStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: agent
func (_m *MockAgentStore) Save(agent *config.AgentConfig) error {
	ret := _m.Called(agent)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.AgentConfig) error); ok {
		r0 = rf(agent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAgentStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - agent *config.AgentConfig
func (_e *MockAgentStore_Expecter) Save(agent interface{}) *MockAgentStore_Save_Call {
	return &MockAgentStore_Save_Call{Call: _e.mock.On("Save", agent)}
}

func (_c *MockAgentStore_Save_Call) Run(run func(agent *config.AgentConfig)) *MockAgentStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.AgentConfig))
	})
	return _c
}

func (_c *MockAgentStore_Save_Call) Return(_a0 error) *MockAgentStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentStore_Save_Call) RunAndReturn(run func(*config.AgentConfig) error) *MockAgentStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentStore creates a new instance of MockAgentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentStore {
	mock := &MockAgentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
