// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	storage "github.com/shaharia-lab/agento/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// MockTaskStore is an autogenerated mock type for the TaskStore type
type MockTaskStore struct {
	mock.Mock
}

type MockTaskStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskStore) EXPECT() *MockTaskStore_Expecter {
	return &MockTaskStore_Expecter{mock: &_m.Mock}
}

// BulkDeleteJobHistory provides a mock function with given fields: ids
func (_m *MockTaskStore) BulkDeleteJobHistory(ids []string) error {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDeleteJobHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_BulkDeleteJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDeleteJobHistory'
type MockTaskStore_BulkDeleteJobHistory_Call struct {
	*mock.Call
}

// BulkDeleteJobHistory is a helper method to define mock.On call
//   - ids []string
func (_e *MockTaskStore_Expecter) BulkDeleteJobHistory(ids interface{}) *MockTaskStore_BulkDeleteJobHistory_Call {
	return &MockTaskStore_BulkDeleteJobHistory_Call{Call: _e.mock.On("BulkDeleteJobHistory", ids)}
}

func (_c *MockTaskStore_BulkDeleteJobHistory_Call) Run(run func(ids []string)) *MockTaskStore_BulkDeleteJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockTaskStore_BulkDeleteJobHistory_Call) Return(_a0 error) *MockTaskStore_BulkDeleteJobHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_BulkDeleteJobHistory_Call) RunAndReturn(run func([]string) error) *MockTaskStore_BulkDeleteJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJobHistory provides a mock function with given fields: jh
func (_m *MockTaskStore) CreateJobHistory(jh *storage.JobHistory) error {
	ret := _m.Called(jh)

	if len(ret) == 0 {
		panic("no return value specified for CreateJobHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*storage.JobHistory) error); ok {
		r0 = rf(jh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_CreateJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJobHistory'
type MockTaskStore_CreateJobHistory_Call struct {
	*mock.Call
}

// CreateJobHistory is a helper method to define mock.On call
//   - jh *storage.JobHistory
func (_e *MockTaskStore_Expecter) CreateJobHistory(jh interface{}) *MockTaskStore_CreateJobHistory_Call {
	return &MockTaskStore_CreateJobHistory_Call{Call: _e.mock.On("CreateJobHistory", jh)}
}

func (_c *MockTaskStore_CreateJobHistory_Call) Run(run func(jh *storage.JobHistory)) *MockTaskStore_CreateJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*storage.JobHistory))
	})
	return _c
}

func (_c *MockTaskStore_CreateJobHistory_Call) Return(_a0 error) *MockTaskStore_CreateJobHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_CreateJobHistory_Call) RunAndReturn(run func(*storage.JobHistory) error) *MockTaskStore_CreateJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function with given fields: task
func (_m *MockTaskStore) CreateTask(task *storage.ScheduledTask) error {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*storage.ScheduledTask) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskStore_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - task *storage.ScheduledTask
func (_e *MockTaskStore_Expecter) CreateTask(task interface{}) *MockTaskStore_CreateTask_Call {
	return &MockTaskStore_CreateTask_Call{Call: _e.mock.On("CreateTask", task)}
}

func (_c *MockTaskStore_CreateTask_Call) Run(run func(task *storage.ScheduledTask)) *MockTaskStore_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*storage.ScheduledTask))
	})
	return _c
}

func (_c *MockTaskStore_CreateTask_Call) Return(_a0 error) *MockTaskStore_CreateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_CreateTask_Call) RunAndReturn(run func(*storage.ScheduledTask) error) *MockTaskStore_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJobHistory provides a mock function with given fields: id
func (_m *MockTaskStore) DeleteJobHistory(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJobHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_DeleteJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJobHistory'
type MockTaskStore_DeleteJobHistory_Call struct {
	*mock.Call
}

// DeleteJobHistory is a helper method to define mock.On call
//   - id string
func (_e *MockTaskStore_Expecter) DeleteJobHistory(id interface{}) *MockTaskStore_DeleteJobHistory_Call {
	return &MockTaskStore_DeleteJobHistory_Call{Call: _e.mock.On("DeleteJobHistory", id)}
}

func (_c *MockTaskStore_DeleteJobHistory_Call) Run(run func(id string)) *MockTaskStore_DeleteJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTaskStore_DeleteJobHistory_Call) Return(_a0 error) *MockTaskStore_DeleteJobHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_DeleteJobHistory_Call) RunAndReturn(run func(string) error) *MockTaskStore_DeleteJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function with given fields: id
func (_m *MockTaskStore) DeleteTask(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockTaskStore_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - id string
func (_e *MockTaskStore_Expecter) DeleteTask(id interface{}) *MockTaskStore_DeleteTask_Call {
	return &MockTaskStore_DeleteTask_Call{Call: _e.mock.On("DeleteTask", id)}
}

func (_c *MockTaskStore_DeleteTask_Call) Run(run func(id string)) *MockTaskStore_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTaskStore_DeleteTask_Call) Return(_a0 error) *MockTaskStore_DeleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_DeleteTask_Call) RunAndReturn(run func(string) error) *MockTaskStore_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobHistory provides a mock function with given fields: id
func (_m *MockTaskStore) GetJobHistory(id string) (*storage.JobHistory, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetJobHistory")
	}

	var r0 *storage.JobHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*storage.JobHistory, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *storage.JobHistory); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.JobHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_GetJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobHistory'
type MockTaskStore_GetJobHistory_Call struct {
	*mock.Call
}

// GetJobHistory is a helper method to define mock.On call
//   - id string
func (_e *MockTaskStore_Expecter) GetJobHistory(id interface{}) *MockTaskStore_GetJobHistory_Call {
	return &MockTaskStore_GetJobHistory_Call{Call: _e.mock.On("GetJobHistory", id)}
}

func (_c *MockTaskStore_GetJobHistory_Call) Run(run func(id string)) *MockTaskStore_GetJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTaskStore_GetJobHistory_Call) Return(_a0 *storage.JobHistory, _a1 error) *MockTaskStore_GetJobHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_GetJobHistory_Call) RunAndReturn(run func(string) (*storage.JobHistory, error)) *MockTaskStore_GetJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: id
func (_m *MockTaskStore) GetTask(id string) (*storage.ScheduledTask, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *storage.ScheduledTask
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*storage.ScheduledTask, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *storage.ScheduledTask); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ScheduledTask)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockTaskStore_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - id string
func (_e *MockTaskStore_Expecter) GetTask(id interface{}) *MockTaskStore_GetTask_Call {
	return &MockTaskStore_GetTask_Call{Call: _e.mock.On("GetTask", id)}
}

func (_c *MockTaskStore_GetTask_Call) Run(run func(id string)) *MockTaskStore_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTaskStore_GetTask_Call) Return(_a0 *storage.ScheduledTask, _a1 error) *MockTaskStore_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_GetTask_Call) RunAndReturn(run func(string) (*storage.ScheduledTask, error)) *MockTaskStore_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllJobHistory provides a mock function with given fields: limit, offset
func (_m *MockTaskStore) ListAllJobHistory(limit int, offset int) ([]*storage.JobHistory, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAllJobHistory")
	}

	var r0 []*storage.JobHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]*storage.JobHistory, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []*storage.JobHistory); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.JobHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_ListAllJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllJobHistory'
type MockTaskStore_ListAllJobHistory_Call struct {
	*mock.Call
}

// ListAllJobHistory is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockTaskStore_Expecter) ListAllJobHistory(limit interface{}, offset interface{}) *MockTaskStore_ListAllJobHistory_Call {
	return &MockTaskStore_ListAllJobHistory_Call{Call: _e.mock.On("ListAllJobHistory", limit, offset)}
}

func (_c *MockTaskStore_ListAllJobHistory_Call) Run(run func(limit int, offset int)) *MockTaskStore_ListAllJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockTaskStore_ListAllJobHistory_Call) Return(_a0 []*storage.JobHistory, _a1 error) *MockTaskStore_ListAllJobHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_ListAllJobHistory_Call) RunAndReturn(run func(int, int) ([]*storage.JobHistory, error)) *MockTaskStore_ListAllJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListJobHistory provides a mock function with given fields: taskID, limit
func (_m *MockTaskStore) ListJobHistory(taskID string, limit int) ([]*storage.JobHistory, error) {
	ret := _m.Called(taskID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListJobHistory")
	}

	var r0 []*storage.JobHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]*storage.JobHistory, error)); ok {
		return rf(taskID, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []*storage.JobHistory); ok {
		r0 = rf(taskID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.JobHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(taskID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_ListJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJobHistory'
type MockTaskStore_ListJobHistory_Call struct {
	*mock.Call
}

// ListJobHistory is a helper method to define mock.On call
//   - taskID string
//   - limit int
func (_e *MockTaskStore_Expecter) ListJobHistory(taskID interface{}, limit interface{}) *MockTaskStore_ListJobHistory_Call {
	return &MockTaskStore_ListJobHistory_Call{Call: _e.mock.On("ListJobHistory", taskID, limit)}
}

func (_c *MockTaskStore_ListJobHistory_Call) Run(run func(taskID string, limit int)) *MockTaskStore_ListJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockTaskStore_ListJobHistory_Call) Return(_a0 []*storage.JobHistory, _a1 error) *MockTaskStore_ListJobHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_ListJobHistory_Call) RunAndReturn(run func(string, int) ([]*storage.JobHistory, error)) *MockTaskStore_ListJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with no fields
func (_m *MockTaskStore) ListTasks() ([]*storage.ScheduledTask, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []*storage.ScheduledTask
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*storage.ScheduledTask, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*storage.ScheduledTask); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.ScheduledTask)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockTaskStore_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
func (_e *MockTaskStore_Expecter) ListTasks() *MockTaskStore_ListTasks_Call {
	return &MockTaskStore_ListTasks_Call{Call: _e.mock.On("ListTasks")}
}

func (_c *MockTaskStore_ListTasks_Call) Run(run func()) *MockTaskStore_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskStore_ListTasks_Call) Return(_a0 []*storage.ScheduledTask, _a1 error) *MockTaskStore_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_ListTasks_Call) RunAndReturn(run func() ([]*storage.ScheduledTask, error)) *MockTaskStore_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobHistory provides a mock function with given fields: jh
func (_m *MockTaskStore) UpdateJobHistory(jh *storage.JobHistory) error {
	ret := _m.Called(jh)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*storage.JobHistory) error); ok {
		r0 = rf(jh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_UpdateJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobHistory'
type MockTaskStore_UpdateJobHistory_Call struct {
	*mock.Call
}

// UpdateJobHistory is a helper method to define mock.On call
//   - jh *storage.JobHistory
func (_e *MockTaskStore_Expecter) UpdateJobHistory(jh interface{}) *MockTaskStore_UpdateJobHistory_Call {
	return &MockTaskStore_UpdateJobHistory_Call{Call: _e.mock.On("UpdateJobHistory", jh)}
}

func (_c *MockTaskStore_UpdateJobHistory_Call) Run(run func(jh *storage.JobHistory)) *MockTaskStore_UpdateJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*storage.JobHistory))
	})
	return _c
}

func (_c *MockTaskStore_UpdateJobHistory_Call) Return(_a0 error) *MockTaskStore_UpdateJobHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_UpdateJobHistory_Call) RunAndReturn(run func(*storage.JobHistory) error) *MockTaskStore_UpdateJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: task
func (_m *MockTaskStore) UpdateTask(task *storage.ScheduledTask) error {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*storage.ScheduledTask) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockTaskStore_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - task *storage.ScheduledTask
func (_e *MockTaskStore_Expecter) UpdateTask(task interface{}) *MockTaskStore_UpdateTask_Call {
	return &MockTaskStore_UpdateTask_Call{Call: _e.mock.On("UpdateTask", task)}
}

func (_c *MockTaskStore_UpdateTask_Call) Run(run func(task *storage.ScheduledTask)) *MockTaskStore_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*storage.ScheduledTask))
	})
	return _c
}

func (_c *MockTaskStore_UpdateTask_Call) Return(_a0 error) *MockTaskStore_UpdateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_UpdateTask_Call) RunAndReturn(run func(*storage.ScheduledTask) error) *MockTaskStore_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskStore creates a new instance of MockTaskStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskStore {
	mock := &MockTaskStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
