// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	config "github.com/shaharia-lab/agento/internal/config"

	mock "github.com/stretchr/testify/mock"
)

// MockIntegrationStore is an autogenerated mock type for the IntegrationStore type
type MockIntegrationStore struct {
	mock.Mock
}

type MockIntegrationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIntegrationStore) EXPECT() *MockIntegrationStore_Expecter {
	return &MockIntegrationStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockIntegrationStore) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIntegrationStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIntegrationStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIntegrationStore_Expecter) Delete(ctx interface{}, id interface{}) *MockIntegrationStore_Delete_Call {
	return &MockIntegrationStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIntegrationStore_Delete_Call) Run(run func(ctx context.Context, id string)) *MockIntegrationStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIntegrationStore_Delete_Call) Return(_a0 error) *MockIntegrationStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntegrationStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockIntegrationStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockIntegrationStore) Get(ctx context.Context, id string) (*config.IntegrationConfig, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *config.IntegrationConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*config.IntegrationConfig, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *config.IntegrationConfig); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.IntegrationConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntegrationStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIntegrationStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIntegrationStore_Expecter) Get(ctx interface{}, id interface{}) *MockIntegrationStore_Get_Call {
	return &MockIntegrationStore_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockIntegrationStore_Get_Call) Run(run func(ctx context.Context, id string)) *MockIntegrationStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIntegrationStore_Get_Call) Return(_a0 *config.IntegrationConfig, _a1 error) *MockIntegrationStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIntegrationStore_Get_Call) RunAndReturn(run func(context.Context, string) (*config.IntegrationConfig, error)) *MockIntegrationStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockIntegrationStore) List(ctx context.Context) ([]*config.IntegrationConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*config.IntegrationConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*config.IntegrationConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*config.IntegrationConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*config.IntegrationConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntegrationStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIntegrationStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIntegrationStore_Expecter) List(ctx interface{}) *MockIntegrationStore_List_Call {
	return &MockIntegrationStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockIntegrationStore_List_Call) Run(run func(ctx context.Context)) *MockIntegrationStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIntegrationStore_List_Call) Return(_a0 []*config.IntegrationConfig, _a1 error) *MockIntegrationStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIntegrationStore_List_Call) RunAndReturn(run func(context.Context) ([]*config.IntegrationConfig, error)) *MockIntegrationStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, cfg
func (_m *MockIntegrationStore) Save(ctx context.Context, cfg *config.IntegrationConfig) error {
	ret := _m.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *config.IntegrationConfig) error); ok {
		r0 = rf(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIntegrationStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIntegrationStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg *config.IntegrationConfig
func (_e *MockIntegrationStore_Expecter) Save(ctx interface{}, cfg interface{}) *MockIntegrationStore_Save_Call {
	return &MockIntegrationStore_Save_Call{Call: _e.mock.On("Save", ctx, cfg)}
}

func (_c *MockIntegrationStore_Save_Call) Run(run func(ctx context.Context, cfg *config.IntegrationConfig)) *MockIntegrationStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*config.IntegrationConfig))
	})
	return _c
}

func (_c *MockIntegrationStore_Save_Call) Return(_a0 error) *MockIntegrationStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntegrationStore_Save_Call) RunAndReturn(run func(context.Context, *config.IntegrationConfig) error) *MockIntegrationStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIntegrationStore creates a new instance of MockIntegrationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIntegrationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIntegrationStore {
	mock := &MockIntegrationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
