// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	storage "github.com/shaharia-lab/agento/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// MockTaskStore is an autogenerated mock type for the TaskStore type
type MockTaskStore struct {
	mock.Mock
}

type MockTaskStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskStore) EXPECT() *MockTaskStore_Expecter {
	return &MockTaskStore_Expecter{mock: &_m.Mock}
}

// BulkDeleteJobHistory provides a mock function with given fields: ctx, ids
func (_m *MockTaskStore) BulkDeleteJobHistory(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDeleteJobHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_BulkDeleteJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDeleteJobHistory'
type MockTaskStore_BulkDeleteJobHistory_Call struct {
	*mock.Call
}

// BulkDeleteJobHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockTaskStore_Expecter) BulkDeleteJobHistory(ctx interface{}, ids interface{}) *MockTaskStore_BulkDeleteJobHistory_Call {
	return &MockTaskStore_BulkDeleteJobHistory_Call{Call: _e.mock.On("BulkDeleteJobHistory", ctx, ids)}
}

func (_c *MockTaskStore_BulkDeleteJobHistory_Call) Run(run func(ctx context.Context, ids []string)) *MockTaskStore_BulkDeleteJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockTaskStore_BulkDeleteJobHistory_Call) Return(_a0 error) *MockTaskStore_BulkDeleteJobHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_BulkDeleteJobHistory_Call) RunAndReturn(run func(context.Context, []string) error) *MockTaskStore_BulkDeleteJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJobHistory provides a mock function with given fields: ctx, jh
func (_m *MockTaskStore) CreateJobHistory(ctx context.Context, jh *storage.JobHistory) error {
	ret := _m.Called(ctx, jh)

	if len(ret) == 0 {
		panic("no return value specified for CreateJobHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.JobHistory) error); ok {
		r0 = rf(ctx, jh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_CreateJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJobHistory'
type MockTaskStore_CreateJobHistory_Call struct {
	*mock.Call
}

// CreateJobHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - jh *storage.JobHistory
func (_e *MockTaskStore_Expecter) CreateJobHistory(ctx interface{}, jh interface{}) *MockTaskStore_CreateJobHistory_Call {
	return &MockTaskStore_CreateJobHistory_Call{Call: _e.mock.On("CreateJobHistory", ctx, jh)}
}

func (_c *MockTaskStore_CreateJobHistory_Call) Run(run func(ctx context.Context, jh *storage.JobHistory)) *MockTaskStore_CreateJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storage.JobHistory))
	})
	return _c
}

func (_c *MockTaskStore_CreateJobHistory_Call) Return(_a0 error) *MockTaskStore_CreateJobHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_CreateJobHistory_Call) RunAndReturn(run func(context.Context, *storage.JobHistory) error) *MockTaskStore_CreateJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *MockTaskStore) CreateTask(ctx context.Context, task *storage.ScheduledTask) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.ScheduledTask) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskStore_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *storage.ScheduledTask
func (_e *MockTaskStore_Expecter) CreateTask(ctx interface{}, task interface{}) *MockTaskStore_CreateTask_Call {
	return &MockTaskStore_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task)}
}

func (_c *MockTaskStore_CreateTask_Call) Run(run func(ctx context.Context, task *storage.ScheduledTask)) *MockTaskStore_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storage.ScheduledTask))
	})
	return _c
}

func (_c *MockTaskStore_CreateTask_Call) Return(_a0 error) *MockTaskStore_CreateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_CreateTask_Call) RunAndReturn(run func(context.Context, *storage.ScheduledTask) error) *MockTaskStore_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJobHistory provides a mock function with given fields: ctx, id
func (_m *MockTaskStore) DeleteJobHistory(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJobHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_DeleteJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJobHistory'
type MockTaskStore_DeleteJobHistory_Call struct {
	*mock.Call
}

// DeleteJobHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskStore_Expecter) DeleteJobHistory(ctx interface{}, id interface{}) *MockTaskStore_DeleteJobHistory_Call {
	return &MockTaskStore_DeleteJobHistory_Call{Call: _e.mock.On("DeleteJobHistory", ctx, id)}
}

func (_c *MockTaskStore_DeleteJobHistory_Call) Run(run func(ctx context.Context, id string)) *MockTaskStore_DeleteJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskStore_DeleteJobHistory_Call) Return(_a0 error) *MockTaskStore_DeleteJobHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_DeleteJobHistory_Call) RunAndReturn(run func(context.Context, string) error) *MockTaskStore_DeleteJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function with given fields: ctx, id
func (_m *MockTaskStore) DeleteTask(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockTaskStore_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskStore_Expecter) DeleteTask(ctx interface{}, id interface{}) *MockTaskStore_DeleteTask_Call {
	return &MockTaskStore_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, id)}
}

func (_c *MockTaskStore_DeleteTask_Call) Run(run func(ctx context.Context, id string)) *MockTaskStore_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskStore_DeleteTask_Call) Return(_a0 error) *MockTaskStore_DeleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_DeleteTask_Call) RunAndReturn(run func(context.Context, string) error) *MockTaskStore_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobHistory provides a mock function with given fields: ctx, id
func (_m *MockTaskStore) GetJobHistory(ctx context.Context, id string) (*storage.JobHistory, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetJobHistory")
	}

	var r0 *storage.JobHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.JobHistory, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.JobHistory); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.JobHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_GetJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobHistory'
type MockTaskStore_GetJobHistory_Call struct {
	*mock.Call
}

// GetJobHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskStore_Expecter) GetJobHistory(ctx interface{}, id interface{}) *MockTaskStore_GetJobHistory_Call {
	return &MockTaskStore_GetJobHistory_Call{Call: _e.mock.On("GetJobHistory", ctx, id)}
}

func (_c *MockTaskStore_GetJobHistory_Call) Run(run func(ctx context.Context, id string)) *MockTaskStore_GetJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskStore_GetJobHistory_Call) Return(_a0 *storage.JobHistory, _a1 error) *MockTaskStore_GetJobHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_GetJobHistory_Call) RunAndReturn(run func(context.Context, string) (*storage.JobHistory, error)) *MockTaskStore_GetJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: ctx, id
func (_m *MockTaskStore) GetTask(ctx context.Context, id string) (*storage.ScheduledTask, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *storage.ScheduledTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.ScheduledTask, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.ScheduledTask); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ScheduledTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockTaskStore_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskStore_Expecter) GetTask(ctx interface{}, id interface{}) *MockTaskStore_GetTask_Call {
	return &MockTaskStore_GetTask_Call{Call: _e.mock.On("GetTask", ctx, id)}
}

func (_c *MockTaskStore_GetTask_Call) Run(run func(ctx context.Context, id string)) *MockTaskStore_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskStore_GetTask_Call) Return(_a0 *storage.ScheduledTask, _a1 error) *MockTaskStore_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_GetTask_Call) RunAndReturn(run func(context.Context, string) (*storage.ScheduledTask, error)) *MockTaskStore_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllJobHistory provides a mock function with given fields: ctx, limit, offset
func (_m *MockTaskStore) ListAllJobHistory(ctx context.Context, limit int, offset int) ([]*storage.JobHistory, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAllJobHistory")
	}

	var r0 []*storage.JobHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*storage.JobHistory, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*storage.JobHistory); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.JobHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_ListAllJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllJobHistory'
type MockTaskStore_ListAllJobHistory_Call struct {
	*mock.Call
}

// ListAllJobHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockTaskStore_Expecter) ListAllJobHistory(ctx interface{}, limit interface{}, offset interface{}) *MockTaskStore_ListAllJobHistory_Call {
	return &MockTaskStore_ListAllJobHistory_Call{Call: _e.mock.On("ListAllJobHistory", ctx, limit, offset)}
}

func (_c *MockTaskStore_ListAllJobHistory_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockTaskStore_ListAllJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTaskStore_ListAllJobHistory_Call) Return(_a0 []*storage.JobHistory, _a1 error) *MockTaskStore_ListAllJobHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_ListAllJobHistory_Call) RunAndReturn(run func(context.Context, int, int) ([]*storage.JobHistory, error)) *MockTaskStore_ListAllJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListJobHistory provides a mock function with given fields: ctx, taskID, limit
func (_m *MockTaskStore) ListJobHistory(ctx context.Context, taskID string, limit int) ([]*storage.JobHistory, error) {
	ret := _m.Called(ctx, taskID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListJobHistory")
	}

	var r0 []*storage.JobHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]*storage.JobHistory, error)); ok {
		return rf(ctx, taskID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*storage.JobHistory); ok {
		r0 = rf(ctx, taskID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.JobHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, taskID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_ListJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJobHistory'
type MockTaskStore_ListJobHistory_Call struct {
	*mock.Call
}

// ListJobHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - limit int
func (_e *MockTaskStore_Expecter) ListJobHistory(ctx interface{}, taskID interface{}, limit interface{}) *MockTaskStore_ListJobHistory_Call {
	return &MockTaskStore_ListJobHistory_Call{Call: _e.mock.On("ListJobHistory", ctx, taskID, limit)}
}

func (_c *MockTaskStore_ListJobHistory_Call) Run(run func(ctx context.Context, taskID string, limit int)) *MockTaskStore_ListJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockTaskStore_ListJobHistory_Call) Return(_a0 []*storage.JobHistory, _a1 error) *MockTaskStore_ListJobHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_ListJobHistory_Call) RunAndReturn(run func(context.Context, string, int) ([]*storage.JobHistory, error)) *MockTaskStore_ListJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with given fields: ctx
func (_m *MockTaskStore) ListTasks(ctx context.Context) ([]*storage.ScheduledTask, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []*storage.ScheduledTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*storage.ScheduledTask, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*storage.ScheduledTask); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.ScheduledTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStore_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockTaskStore_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskStore_Expecter) ListTasks(ctx interface{}) *MockTaskStore_ListTasks_Call {
	return &MockTaskStore_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx)}
}

func (_c *MockTaskStore_ListTasks_Call) Run(run func(ctx context.Context)) *MockTaskStore_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskStore_ListTasks_Call) Return(_a0 []*storage.ScheduledTask, _a1 error) *MockTaskStore_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStore_ListTasks_Call) RunAndReturn(run func(context.Context) ([]*storage.ScheduledTask, error)) *MockTaskStore_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobHistory provides a mock function with given fields: ctx, jh
func (_m *MockTaskStore) UpdateJobHistory(ctx context.Context, jh *storage.JobHistory) error {
	ret := _m.Called(ctx, jh)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.JobHistory) error); ok {
		r0 = rf(ctx, jh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_UpdateJobHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobHistory'
type MockTaskStore_UpdateJobHistory_Call struct {
	*mock.Call
}

// UpdateJobHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - jh *storage.JobHistory
func (_e *MockTaskStore_Expecter) UpdateJobHistory(ctx interface{}, jh interface{}) *MockTaskStore_UpdateJobHistory_Call {
	return &MockTaskStore_UpdateJobHistory_Call{Call: _e.mock.On("UpdateJobHistory", ctx, jh)}
}

func (_c *MockTaskStore_UpdateJobHistory_Call) Run(run func(ctx context.Context, jh *storage.JobHistory)) *MockTaskStore_UpdateJobHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storage.JobHistory))
	})
	return _c
}

func (_c *MockTaskStore_UpdateJobHistory_Call) Return(_a0 error) *MockTaskStore_UpdateJobHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_UpdateJobHistory_Call) RunAndReturn(run func(context.Context, *storage.JobHistory) error) *MockTaskStore_UpdateJobHistory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: ctx, task
func (_m *MockTaskStore) UpdateTask(ctx context.Context, task *storage.ScheduledTask) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.ScheduledTask) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStore_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockTaskStore_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *storage.ScheduledTask
func (_e *MockTaskStore_Expecter) UpdateTask(ctx interface{}, task interface{}) *MockTaskStore_UpdateTask_Call {
	return &MockTaskStore_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, task)}
}

func (_c *MockTaskStore_UpdateTask_Call) Run(run func(ctx context.Context, task *storage.ScheduledTask)) *MockTaskStore_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storage.ScheduledTask))
	})
	return _c
}

func (_c *MockTaskStore_UpdateTask_Call) Return(_a0 error) *MockTaskStore_UpdateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStore_UpdateTask_Call) RunAndReturn(run func(context.Context, *storage.ScheduledTask) error) *MockTaskStore_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskStore creates a new instance of MockTaskStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskStore {
	mock := &MockTaskStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
